name: Push tagged version to container registry

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  docker-push:
    permissions:
      contents: read
      packages: write
    uses: Cyberbeni/workflows/.github/workflows/docker-push.yml@master
    with:
      image_name: ${{ github.repository }}
