name: SwiftFormat lint

on:
  pull_request:
  push:
    branches: master

jobs:
  swiftformat-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v3
      with:
        url: https://github.com/nicklockwood/SwiftFormat
    - name: Lint
      run: swiftformat --lint .
